# .github/workflows/deploy.yml

name: Deploy to AWS EC2

# This workflow is triggered on pushes to the 'main' branch
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is named 'deploy'
  deploy:
    name: Deploy to EC2
    # The type of runner that the job will run on. We use the latest Ubuntu version.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Step 1: Check out the repository code so the workflow can access it
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: SSH into the EC2 instance and run the deployment script
    - name: Deploy to EC2 instance
      # Using a popular and well-maintained action for SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        # The public IP address or DNS of your EC2 instance
        host: ${{ secrets.EC2_HOST }}
        # The username to connect with (e.g., ec2-user, ubuntu)
        username: ${{ secrets.EC2_USERNAME }}
        # Your private SSH key
        key: ${{ secrets.SSH_KEY }}
        # The script to execute on the remote server
        script: |
          sh /home/ubuntu/SiteSnap/deploy.sh